FROM ubuntu

RUN apt-get update && \
      apt-get -y install xdg-user-dirs 

RUN xdg-user-dirs-update

COPY target/debian/wechsel_0.2.4-1_amd64.deb /wechsel.deb
COPY target/release/wechsel_testing /test
RUN dpkg -i wechsel.deb

CMD ./test