#!/bin/bash

#Reload Indicator
gdbus call -e -d org.gnome.shell.extensions.wechsel -o /org/gnome/shell/extensions/wechsel/service -m org.gnome.shell.extensions.wechsel.service.Reload > /dev/null;\


#Reload Ding Desktop Icons
#gdbus call -e -d org.gnome.Nautilus -o /org/gnome/Nautilus/window/$i -m org.gtk.Actions.Activate "@s 'reload'" "@av []" "@a{sv} {}" > /dev/null;\

# Set gnome wallpapers
# This is searching for images named wallpaper.png and wallpaper_dark.png
# Light mode wallpaper
#wallpaper=$PRJ_PATH/wallpaper.png
#if [ -f $wallpaper  ]; then
#       gsettings set org.gnome.desktop.background picture-uri file://$wallpaper
#else
#       gsettings set org.gnome.desktop.background picture-uri file:///usr/share/backgrounds/f38/default/f38-01-day.png
#fi

# Dark mode wallpaper
#wallpaper=$PRJ_PATH/wallpaper_dark.png
#if [ -f $wallpaper ]; then
#       gsettings set org.gnome.desktop.background picture-uri-dark file://$wallpaper
#else
#       gsettings set org.gnome.desktop.background picture-uri-dark file:///usr/share/backgrounds/f38/default/f38-01-night.png
#fi

# Call project specific on-prj-change
on_change=$PRJ_PATH/.on-prj-change
if [ -f $on_change ]; then
        $on_change
fi
